# Generated by Django 3.1 on 2020-09-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcreator',
            old_name='passwordOrg',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='userEmail',
        ),
    ]
