# Generated by Django 3.1 on 2020-09-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200928_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcreator',
            name='orgemail',
        ),
        migrations.RemoveField(
            model_name='jobcreator',
            name='password',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='password',
        ),
    ]
