# Generated by Django 3.1 on 2020-09-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200929_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcreator',
            name='industry',
        ),
    ]
