# Generated by Django 3.1 on 2020-09-30 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_jobcreator_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('category1', models.CharField(max_length=100)),
                ('category2', models.CharField(max_length=100)),
                ('category3', models.CharField(max_length=100)),
                ('category4', models.CharField(max_length=100)),
                ('category5', models.CharField(max_length=100)),
                ('category6', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
