# Generated by Django 3.1.2 on 2020-10-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200930_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobrec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('jobid', models.CharField(default='Dice:', max_length=50)),
                ('jobtitle', models.TextField(verbose_name=50)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.TextField(default='c'),
        ),
        migrations.DeleteModel(
            name='skills',
        ),
    ]
