# Generated by Django 3.1.2 on 2020-10-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_jobseeker_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobrec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('jobtitle', models.TextField(verbose_name=50)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='skills',
        ),
    ]
