# Generated by Django 3.1.2 on 2020-10-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201006_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrec',
            name='jobid',
            field=models.CharField(default='Dice:', max_length=50),
        ),
    ]
