# Generated by Django 3.1 on 2021-02-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201009_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrec',
            name='advertiserurl',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
