# Generated by Django 3.1.1 on 2021-02-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_jobrec_advertiserurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrec',
            name='company',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='jobrec',
            name='jobdescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrec',
            name='joblocation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrec',
            name='jobstatus',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
