# Generated by Django 3.1 on 2021-02-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_jobrec_advertiserurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrec',
            name='company',
            field=models.CharField(default='null', max_length=2000),
        ),
        migrations.AddField(
            model_name='jobrec',
            name='jobdescription',
            field=models.TextField(default='Job Description'),
        ),
        migrations.AddField(
            model_name='jobrec',
            name='joblocation',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='jobrec',
            name='jobstatus',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
