# Generated by Django 3.1.1 on 2021-02-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210224_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrec',
            name='company',
            field=models.CharField(default='null', max_length=2000),
        ),
        migrations.AlterField(
            model_name='jobrec',
            name='jobdescription',
            field=models.TextField(default='Job Description'),
        ),
        migrations.AlterField(
            model_name='jobrec',
            name='jobstatus',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
