# Generated by Django 3.1 on 2021-02-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210226_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrec',
            name='jobid',
        ),
    ]
