# Generated by Django 3.1 on 2021-02-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoblistTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiserurl', models.CharField(blank=True, max_length=500, null=True)),
                ('company', models.CharField(blank=True, max_length=2000, null=True)),
                ('jobstatus', models.CharField(blank=True, max_length=500, null=True)),
                ('jobdescription', models.TextField(blank=True, null=True)),
                ('joblocation', models.CharField(blank=True, max_length=200, null=True)),
                ('jobtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('salary', models.IntegerField(default=60000, null=True)),
            ],
        ),
    ]
