# Generated by Django 3.1.2 on 2020-10-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrec', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoblistTable',
        ),
    ]
