# Generated by Django 3.1 on 2021-02-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisttable',
            name='salary',
        ),
    ]
