# Generated by Django 3.1 on 2020-10-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrec', '0002_auto_20201009_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisttable',
            name='company',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
