# Generated by Django 3.1.6 on 2021-02-22 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobrec', '0004_auto_20201009_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('jobid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('jobdescription', models.TextField(blank=True, null=True)),
                ('jobtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='joblisttable',
            name='createruser',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
