# Generated by Django 3.1 on 2021-02-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrec', '0006_auto_20210226_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisttable',
            name='createruser',
        ),
    ]
