# Generated by Django 3.1 on 2021-02-26 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobrec', '0007_remove_joblisttable_createruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisttable',
            name='createruser',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
